version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    # Disable version updates and keep only security updates
    open-pull-requests-limit: 0
