name: 'Create Release Pull Request'

on: create

jobs:
  build:
    name: Create Release Pull Request
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        if: |
          startsWith(github.ref, 'refs/heads/releases/') && !contains(github.ref, 'test')

      - name: Create Pull Request content
        if: |
          startsWith(github.ref, 'refs/heads/releases/') && !contains(github.ref, 'test')
        run: |
          PR_TITLE=`./script/draft-release/release-pr-content.sh title ${GITHUB_REF#refs/heads/}`
          PR_BODY=`./script/draft-release/release-pr-content.sh body ${GITHUB_REF#refs/heads/}`

          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "PR_TITLE<<EOF" >> $GITHUB_ENV
          echo "$PR_TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/create-github-app-token@v3
        id: generate-token
        if: |
          startsWith(github.ref, 'refs/heads/releases/') && !contains(github.ref, 'test')
        with:
          client-id: ${{ secrets.DESKTOP_RELEASES_APP_ID }}
          private-key: ${{ secrets.DESKTOP_RELEASES_APP_PRIVATE_KEY }}

      - name: Create Release Pull Request
        if: |
          startsWith(github.ref, 'refs/heads/releases/') && !contains(github.ref, 'test')
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh pr create \
            --head "${{ github.ref_name }}" \
            --base development \
            --title "$PR_TITLE" \
            --body "$PR_BODY" \
            --draft
