#!/usr/bin/env node

'use strict'

const path = require('path')
const cp = require('child_process')
const distInfo = require('./dist-info')

const distPath = distInfo.getDistPath()

let binaryPath = ''
if (process.platform === 'darwin') {
  binaryPath = path.join(distPath, 'GitHub.app', 'Contents', 'MacOS', 'GitHub')
} else if (process.platform === 'win32') {
  binaryPath = path.join(distPath, 'GitHub')
} else {
  console.error(`I dunno how to run on ${process.arch} :(`)
  process.exit(1)
}

cp.spawn(binaryPath, [], {env: process.env})
