#!/bin/sh

curl -H "Authorization: token ${DESKTOPBOT_TOKEN}" -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/desktop/desktop-secrets/contents/developer-id-cert.p12

security import developer-id-cert.p12 -P $KEY_PASSWORD -T /usr/bin/codesign
