#!/usr/bin/env node

'use strict'

const express = require('express')
const webpack = require('webpack')
const config = require('../app/webpack.development')
const run = require('./run')

const server = express()
const compiler = webpack(config)
const port = process.env.PORT || 3000

server.use(require('webpack-dev-middleware')(compiler, {
  publicPath: config.output.publicPath,
  noInfo: true
}))

server.use(require('webpack-hot-middleware')(compiler))

server.listen(port, 'localhost', err => {
  if (err) {
    console.log(err)
    process.exit(1)
    return
  }

  console.log(`Server running at http://localhost:${port}`)

  const runningApp = run()
  if (!runningApp) {
    console.error("Couldn't launch the app. You probably need to build it first. Run `npm run build:dev`.")
    process.exit(1)
  }

  runningApp.on('close', () => {
    process.exit(0)
  })
})
