#!/usr/bin/env node

'use strict'

const fs = require('fs')
const path = require('path')
const cp = require('child_process')
const { getUserDataPath, getDistPath, getProductName } = require('./dist-info')

const isFork = process.env.TRAVIS_SECURE_ENV_VARS !== 'true'

if (process.platform === 'darwin' && process.env.TRAVIS && !isFork) {
  const archive = `${getDistPath()}/${getProductName()}.app`
  try {
    console.log('validating signature of Desktop app')
    cp.execSync(`codesign -dv --verbose=4 '${archive}'`)
  } catch (err) {
    process.exit(1)
  }
}

if (process.platform === 'darwin' && process.env.TRAVIS) {
  const directory = getUserDataPath()
  if (fs.existsSync(directory)) {
    console.log(`clearing application data directory ${directory}`)
    fs.rmdirSync(directory)
  }
}

const output = cp.execSync('git config -l --show-origin', { encoding: 'utf-8' })
console.log(`${output}\n\n`)

// clear existing log files
const directory = getUserDataPath()
const logsDir = path.join(directory, 'logs')
if (!fs.existsSync(logsDir)) {
  return
}

const files = fs.readdirSync(logsDir)
files.forEach(file => {
  if (file.endsWith('.log')) {
    console.log(`deleting ${file}`)
    const fullPath = path.join(directory, file)
    fs.unlinkSync(fullPath)
  }
})
