#!/usr/bin/env node

'use strict'

const fs = require('fs')
const path = require('path')
const { getUserDataPath } = require('./dist-info')

function reviewLogs() {
  const directory = getUserDataPath()
  if (!fs.existsSync(directory)) {
    return
  }

  const files = fs.readdirSync(directory)
    files.forEach(file => {
      if (file.endsWith('.log')) {
        console.log(`opening ${file}`)
        const fullPath = path.join(directory, file)
        const text = fs.readFileSync(fullPath, 'utf-8')
        console.log(text)
      }
  })
}

if (process.platform === 'darwin') {
  if (process.env.TRAVIS_TEST_RESULT === '1') {
    reviewLogs()
  }
}

if (process.platform === 'win32') {
  if (process.env.APPVEYOR_TEST_RESULT !== '0') {
    reviewLogs()
  }
}
