#!/usr/bin/env node

'use strict'

const fs = require('fs')
const path = require('path')
const cp = require('child_process')
const { getUserDataPath } = require('./dist-info')

function setGlobalConfigValueIfNotFound(key, value) {
  try {
    cp.execSync(`git config ${key}`, { encoding: 'utf-8' })
  } catch (err) {
    // config value not found: execSync will return an exit code of -1 and throw
    cp.execSync(`git config --global ${key} "${value}"`, { encoding: 'utf-8' })
  }
}

// ensure we have a user.name and user.email set on this machine for committing
setGlobalConfigValueIfNotFound('user.name', 'Some User')
setGlobalConfigValueIfNotFound('user.email', 'some.user@not-a-real-site.com')

// clear out existing log files
const directory = getUserDataPath()
if (!fs.existsSync(directory)) {
  return
}

const files = fs.readdirSync(directory)
files.forEach(file => {
  if (file.endsWith('.log')) {
    console.log(`deleting ${file}`)
    const fullPath = path.join(directory, file)
    fs.unlinkSync(fullPath)
  }
})
