#!/usr/bin/env node

'use strict'

const run = require('./run')
const express = require('express')
const webpack = require('webpack')
const configs = require('../app/webpack.development')

function startApp() {
  const runningApp = run({ stdio: 'inherit' })
  if (!runningApp) {
    console.error(
      "Couldn't launch the app. You probably need to build it first. Run `yarn build:dev`."
    )
    process.exit(1)
  }

  runningApp.on('close', () => {
    process.exit(0)
  })
}

if (process.env.NODE_ENV === 'production') {
  startApp()
  return
}

const [mainConfig, rendererConfig, askPassConfig] = configs

const server = express()
const compiler = webpack(rendererConfig)
const port = process.env.PORT || 3000

server.use(
  require('webpack-dev-middleware')(compiler, {
    publicPath: rendererConfig.output.publicPath,
    noInfo: true,
  })
)

server.use(require('webpack-hot-middleware')(compiler))

server.listen(port, 'localhost', err => {
  if (err) {
    console.log(err)
    process.exit(1)
    return
  }

  console.log(`Server running at http://localhost:${port}`)
  startApp()
})
