import { focusWindow } from '../../../ui/main-process-proxy'
import {
  DesktopNotification,
  initializeNotifications,
  supportsNotifications,
} from 'desktop-notifications'
import { findToastActivatorClsid } from '../../find-toast-activator-clsid'

let windowsToastActivatorClsid: string | undefined = undefined

function initializeWindowsNotifications() {
  if (windowsToastActivatorClsid !== undefined) {
    return
  }

  windowsToastActivatorClsid = findToastActivatorClsid()

  if (windowsToastActivatorClsid === undefined) {
    log.error(
      'Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.'
    )

    // This is generated by Squirrel.Windows here:
    // https://github.com/Squirrel/Squirrel.Windows/blob/7396fa50ccebf97e28c79ef519c07cb9eee121be/src/Squirrel/UpdateManager.ApplyReleases.cs#L258
    windowsToastActivatorClsid = '{27D44D0C-A542-5B90-BCDB-AC3126048BA2}'
  }

  log.info(`Using toast activator CLSID ${windowsToastActivatorClsid}`)
  initializeNotifications(windowsToastActivatorClsid)
}

/**
 * Shows a notification with a title, a body, and a function to handle when the
 * user clicks on the notification.
 */
export function showNotification(
  title: string,
  body: string,
  onClick: () => void
) {
  if (supportsNotifications()) {
    initializeWindowsNotifications()

    const notification = new DesktopNotification(title, body)
    notification.onclick = () => {
      focusWindow()
      onClick()
    }
    notification.show()
    return
  }

  const notification = new Notification(title, {
    body,
  })

  notification.onclick = () => {
    focusWindow()
    onClick()
  }
}
